name: Scheduled Tests

on:
  push: {}
  pull_request:
    branches:
      - slack-messages-in-pytest-from-biothings
  workflow_dispatch: # Manual trigger
  schedule: # Scheduled trigger
    - cron: "0 6 * * 1-5"  # Runs every weekday at 6 AM UTC

jobs:
  run_app_tests:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: "biothings-codebuild"
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: "#observability-test"
      APPLICATION_NAME: "mygeneset.info"
      APPLICATION_METADATA_PATH: "https://mygene.info/metadata"
      PYTEST_PATH: "src/tests/test_remote.py"

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m venv .venv_test
          source .venv_test/bin/activate
          pip install -r requirements_web.txt
          pip install pytest boto3
          BIOTHINGS_CONFTEST_LOCATION="/biothings/tests/conftest_slack/conftest.py"
          BIOTHINGS_PACKAGE_LOCATION=$(pip show "$PACKAGE_NAME" | grep 'Location:' | awk '{print $2}')
          CONFTEST_PATH="$BIOTHINGS_PACKAGE_LOCATION$BIOTHINGS_CONFTEST_LOCATION"
          cp "$CONFTEST_PATH" .
          /biothings/tests/conftest_slack/conftest.py
          cp .venv/lib/python3.11/site-packages/biothings/tests/conftest_slack/conftest.py src/tests/
          python -m pytest src/tests/test_remote.py -s -vv -k test_query_default_fields --aws-access-key-id="$AWS_ACCESS_KEY_ID" --aws-secret-access-key="$AWS_SECRET_ACCESS_KEY" --aws-region="$AWS_REGION" --aws-s3-bucket="$AWS_S3_BUCKET" --slack-webhook-url="$SLACK_WEBHOOK_URL" --slack-channel="$SLACK_CHANNEL" --application-name="$APPLICATION_NAME" --github-event-name="" --pytest-path="$PYTEST_PATH" --application-metadata-path="$APPLICATION_METADATA_PATH"

      - name: Setup tmate debug session on failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
