name: Scheduled Tests

on:
  push: {}
  pull_request:
    branches:
      - slack-messages-in-pytest-from-biothings
  workflow_dispatch: # Manual trigger
  schedule: # Scheduled trigger
    - cron: "0 6 * * 1-5"  # Runs every weekday at 6 AM UTC

jobs:
  run_app_tests:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key ID.
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key.
      AWS_REGION: ${{ secrets.AWS_REGION }} # AWS Default Region.
      AWS_S3_BUCKET: "biothings-codebuild" # The S3 bucket name for storing application metadata.
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # The Slack webhook URL for sending notifications.
      SLACK_CHANNEL: "#observability-test" # The Slack channel where notifications will be posted.
      APPLICATION_NAME: "mygeneset.info" # The name of the application being tested. It will be displayed in the Slack message.
      APPLICATION_METADATA_PATH: "https://mygene.info/metadata" # Path to the application metadata, typically a URL.
      APPLICATION_METADATA_FIELD: "build_version" # Notation to the build version field. Ex.: "metadata.build_version"
      PYTEST_PATH: "src/tests/test_remote.py" # Path to the Pytest test files.

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m venv .venv_test
          source .venv_test/bin/activate
          pip install -r requirements_web.txt
          pip install pytest boto3
          BIOTHINGS_CONFTEST_LOCATION="/biothings/tests/conftest_slack/conftest.py"
          BIOTHINGS_PACKAGE_LOCATION=$(pip show biothings | grep 'Location:' | awk '{print $2}')
          CONFTEST_PATH="$BIOTHINGS_PACKAGE_LOCATION$BIOTHINGS_CONFTEST_LOCATION"
          cp "$CONFTEST_PATH" .
          python -m pytest src/tests/test_remote.py -s -vv -k test_query_default_fields

      - name: Setup tmate debug session on failure
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
