
name: User Geneset Tests

on:
  push: {}
  pull_request:
    branches:
      - test_github_actions

jobs:    
  run_user_geneset_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    # services:
    #   Elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    #     env:
    #       discovery.type : single-node
    #       xpack.security.enabled: false
    #       xpack.security.http.ssl.enabled: false
    #       xpack.security.transport.ssl.enabled: false
    #     ports:
    #       - 9200:9200
    # container: node:10.18-jessie
    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.5.0
          security-enabled: false
      - name: Create ES Index
        run: curl -X PUT http://localhost:9200/user_genesets

      # - name: Clone frontend repo
      #   run: git clone https://github.com/biothings/mygeneset.info-website
      #   # run: git clone --single-branch --branch development https://github.com/biothings/mygeneset.info-website
      # - name: Setup Node
      #   uses: actions/setup-node@v2
      #   with: 
      #     node-version: '16.17'
      # - name: Build frontend
      #   # run: npm install && npm run build
      #   run: npm i @vue/cli-service && npm install && npm build
      #   working-directory: mygeneset.info-website
      #   env:
      #     NODE_ENV: production

      - name: Create ES Index
        run: curl -X PUT http://localhost:9200/user_genesets
      - name: Clone frontend repo
        uses: actions/checkout@v3
        with:
          repository: biothings/mygeneset.info-website
          path: mygeneset.info-website
      - name: Set up Node
        uses: actions/setup-node@v2
        working-directory: mygeneset.info-website
        with:
          node-version: "16"
      - name: Install packages
        run: yarn install
        working-directory: mygeneset.info-website
      - name: Build app
        run: yarn build
        working-directory: mygeneset.info-website
      - name: Checkout MyGeneset source
        uses: actions/checkout@v2

      - name: Checkout MyGeneset source
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements_web.txt
      - name: Get web config file
        run: wget https://gist.githubusercontent.com/ravila4/9f20d64f51fc23c10b1b70b679a7d3ab/raw/1199ab75b78cc71549fa73e6283810cf2c081682/config.py
        working-directory: src
      - name: Start tornado server
        run: python index.py --webapp &
        working-directory: src
        env:
          ORCID_CLIENT_ID: ${{ secrets.ORCID_CLIENT_ID }}
          ORCID_CLIENT_SECRET: ${{ secrets.ORCID_CLIENT_SECRET }}
      - name: Install PyTest
        run: pip install pytest
      - name: Run App Tests
        run: pytest test_user_genesets.py
        working-directory: src/tests
        env:
          ORCID_USERNAME: ${{ secrets.ORCID_USERNAME }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
